export const FETCH_REPOSITORIES_LOADING = "FETCH_REPOSITORIES_LOADING";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_REPOSITORIES_ERROR = "FETCH_REPOSITORIES_ERROR";
